### ISSUE TITLE
FSR 2.2.2 update?

### ISSUE THREAD

**Issue by TheCodingPsn** [JuanDiegoMontoya/FidelityFX-FSR2#7]

**Comment by JuanDiegoMontoya** [comment]
Hi @TheCodingPsn, thanks for the issue. The FSR 2.2.2 update doesn't reflect a change to the algorithm itself, but rather how it's integrated with the FFX SDK, which isn't relevant to people who just want to integrate this technique. Here are the update notes [from GPUOpen](https://gpuopen.com/fidelityfx-superresolution-2/).

> For 2.2.2
> - Now part of [AMD FidelityFX SDK](https://gpuopen.com/amd-fidelityfx-sdk/).
> - Combined FSR 1 and FSR 2 samples into one sample for the AMD FidelityFX SDK.
